/**
 * Centralized UI copy constants for consistent messaging across the application.
 * Extended with Secretary instance availability states and all required UI copy.
 */

export const uiCopy = {
  product: {
    name: 'Whisper',
  },
  hero: {
    getStartedCta: 'Get Started',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
    loginPrompt: 'Login Required',
    loginDescription: 'Please log in to access this page.',
  },
  secretary: {
    title: 'Secretary',
    greeting: 'Hello! I\'m your Secretary. How can I help you today?',
    menuOptions: [
      'Find your city\'s Whisper instance',
      'Report an issue',
      'View all instances',
      'Create a new instance',
    ],
    noMatchFound: 'I couldn\'t find a match for that. Please try selecting from the menu options.',
    discoveryPromptState: 'Let\'s find your Whisper instance. Which state are you in?',
    discoveryPromptCityOrCounty: 'Great! Now, are you looking for a city or county?',
    discoveryFoundInstance: 'Good news! A Whisper instance exists for your location.',
    foundingCitizenAll: 'Exciting! No instances exist yet for your state, county, or city. You can be a founding citizen!',
    foundingCitizenCityCounty: 'Great opportunity! Instances exist for your state, but not for your county or city. You can be a founding citizen!',
    foundingCitizenCityState: 'Interesting! An instance exists for your county, but not for your city or state. You can be a founding citizen!',
    foundingCitizenCountyState: 'Good news! An instance exists for your city, but not for your county or state. You can be a founding citizen!',
    foundingCitizenCity: 'Almost there! Instances exist for your state and county, but not for your city. You can be a founding citizen!',
    foundingCitizenCounty: 'Close! Instances exist for your state, but not for your county. You can be a founding citizen!',
    foundingCitizenState: 'Opportunity! No instance exists yet for your state. You can be a founding citizen!',
    reportIssueDescriptionPrompt: 'Please describe the issue you\'d like to report.',
    reportIssueSuggestionsPrompt: 'Here are some common categories that might match your issue:',
    reportIssueCategorySelected: 'Great! I\'ll help you create an issue project for that.',
    reportIssueCustomCategory: 'Please enter a custom category for your issue.',
    reportIssueSomethingElse: 'Something else',
    reportIssueNavigating: 'Opening your issue project...',
    typeaheadStatePlaceholder: 'Type to search states...',
    typeaheadCountyPlaceholder: 'Type to search counties...',
    typeaheadCityPlaceholder: 'Type to search cities...',
    typeaheadNoResults: 'No results found',
    typeaheadCountyHelper: 'Select a county:',
    typeaheadCityHelper: 'Or select a city:',
    checkingAvailability: 'Checking instance availability...',
    availabilityCheckError: 'Unable to check availability. Please try again.',
    nudgeTitle: 'Need help?',
    nudgeDescription: 'Ask the Secretary to find your city\'s instance or report an issue.',
    nudgeButton: 'Open Secretary',
  },
  secretaryNudge: {
    title: 'Need help?',
    description: 'Ask the Secretary to find your city\'s instance or report an issue.',
    buttonLabel: 'Open Secretary',
  },
  profile: {
    title: 'Profile',
    editTitle: 'Edit Profile',
    viewTitle: 'Your Profile',
    editProfile: 'Edit Profile',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    saveButton: 'Save Profile',
    editButton: 'Edit Profile',
    logoutButton: 'Logout',
    setupPrompt: 'Welcome! Please set up your profile to continue.',
    bioLabel: 'Bio',
    bioPlaceholder: 'Tell us about yourself...',
    locationLabel: 'Location',
    locationPlaceholder: 'City, State',
    profileImageLabel: 'Profile Image',
    uploadImageButton: 'Upload Image',
    removeImageButton: 'Remove Image',
    deleteAccountButton: 'Request Account Deletion',
    deleteAccountConfirm: 'Are you sure you want to request account deletion? This action cannot be undone.',
    pageDescription: 'Update your profile information and settings.',
    uploadImage: 'Upload Image',
    changeImage: 'Change Image',
    removeImage: 'Remove Image',
    imageHelper: 'Recommended: Square image, max 5MB',
    imageInvalidType: 'Please select a valid image file (JPEG, PNG, GIF, or WebP)',
    imageTooLarge: 'Image must be smaller than 5MB',
    nameRequired: 'Name is required',
    saveSuccess: 'Profile saved successfully',
    saveError: 'Failed to save profile',
    saving: 'Saving...',
  },
  geography: {
    title: 'Geography',
    description: 'Explore U.S. states, counties, and cities.',
    pageTitle: 'Geography',
    pageDescription: 'Explore U.S. states, counties, and cities.',
    backButton: 'Back to Home',
  },
  proposals: {
    title: 'Whisper Instances',
    description: 'Browse and manage Whisper instance proposals',
    refreshButton: 'Refresh',
    loadingMessage: 'Loading proposals...',
    errorMessage: 'Failed to load proposals',
    retryButton: 'Retry',
    emptyState: 'No proposals yet',
    viewDetailsButton: 'View Details',
    geographyLabel: 'Geography',
    levelLabel: 'Level',
    stateLabel: 'State',
    countyLabel: 'County',
    populationLabel: 'Population',
    openIssueProjectButton: 'Open Issue Project',
  },
  createInstance: {
    title: 'Create Instance Proposal',
    description: 'Propose a new Whisper instance for your community',
    stateLabel: 'State',
    countyLabel: 'County',
    placeLabel: 'City/Place',
    instanceNameLabel: 'Instance Name',
    instanceNamePlaceholder: 'WHISPER-YourCity-State',
    whisperNamingHelper: 'Instance names must start with WHISPER-',
    checkingAvailability: 'Checking availability...',
    nameAvailable: 'Name is available',
    nameTaken: 'Name is already taken',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Describe your proposal...',
    cancelButton: 'Cancel',
    submitButton: 'Submit Proposal',
    submitting: 'Submitting...',
  },
  admin: {
    title: 'Admin',
    pageTitle: 'Admin Dashboard',
    pageDescription: 'Manage proposals and moderation queue',
    moderationQueue: 'Moderation Queue',
    authRequiredTitle: 'Authentication Required',
    authRequiredMessage: 'Please log in to access the admin panel.',
    checkingAccessMessage: 'Checking admin access...',
    accessDeniedTitle: 'Access Denied',
    accessDeniedDescription: 'You do not have permission to access this page.',
    recheckAccessButton: 'Recheck Access',
    backButton: 'Back to Home',
    loadingMessage: 'Loading moderation queue...',
    errorTitle: 'Failed to load moderation queue',
    retryButton: 'Retry',
    emptyQueueTitle: 'No items in queue',
    emptyQueueMessage: 'All proposals have been reviewed.',
  },
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    backToHome: 'Back to Home',
    back: 'Back',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    close: 'Close',
  },
} as const;
