export const uiCopy = {
  product: {
    name: 'Whisper',
    tagline: 'Decentralized civic engagement for everyone',
  },
  common: {
    close: 'Close',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    back: 'Back',
  },
  navigation: {
    home: 'Home',
    proposals: 'Proposals',
    createInstance: 'Create Instance',
    admin: 'Admin',
    profile: 'Profile',
    geography: 'Geography',
  },
  hero: {
    title: 'Of the People, By the People , For the People',
    subtitle: 'Whisper is the decentralized platform where citizens report issues, collaborate openly, and resolve them together — rewarding real effort, guaranteeing transparency, and rebuilding trust in local governance from the ground up.',
    primaryCta: 'Get Started',
    secondaryCta: 'Report Issue',
    getStartedCta: 'Get Started',
  },
  features: {
    title: 'Why Whisper?',
    feature1Title: 'Community-Driven',
    feature1Description: 'Every voice matters. Propose, discuss, and vote on local initiatives.',
    feature2Title: 'Transparent & Secure',
    feature2Description: 'Built on blockchain technology for immutable records and trust.',
    feature3Title: 'Scalable Governance',
    feature3Description: 'From neighborhoods to nations, Whisper scales with your community.',
    feature4Title: 'AI-Powered Assistant',
    feature4Description: 'Meet the Secretary—your guide to navigating civic engagement.',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
    loginPrompt: 'Please log in to continue',
    loginDescription: 'You need to be authenticated to access this feature.',
  },
  proposals: {
    title: 'Proposals',
    viewAll: 'View All Proposals',
    noProposals: 'No proposals yet',
    noProposalsDescription: 'Be the first to create a proposal for your community.',
    createProposal: 'Create Proposal',
    status: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
    },
    proposer: 'Proposer',
    description: 'Description',
    geography: 'Geography',
    geographyLabel: 'Geography',
    levelLabel: 'Level',
    stateLabel: 'State',
    countyLabel: 'County',
    population: 'Population',
    populationLabel: 'Population',
    area: 'Area',
    viewDetailsButton: 'View Details',
    openIssueProjectButton: 'Open Issue Project',
    refreshButton: 'Refresh',
    loadingMessage: 'Loading proposals...',
    errorMessage: 'Failed to load proposals',
    retryButton: 'Retry',
    emptyState: 'No proposals available',
  },
  createInstance: {
    title: 'Create Instance',
    yourCityOnWhisper: 'Your City on Whisper',
    yourCityDescription: 'Discover if your city, county, or state already has a Whisper instance, or become a founding citizen.',
    discoverYourCity: 'Discover Your City',
    getStartedTitle: 'Ready to Get Started?',
    getStartedDescription: 'Create a new Whisper instance for your community or explore existing proposals.',
    openSecretary: 'Open Secretary',
    selectState: 'Select State',
    selectCounty: 'Select County',
    selectPlace: 'Select Place (Optional)',
    stateLabel: 'State',
    countyLabel: 'County',
    placeLabel: 'Place (Optional)',
    instanceName: 'Instance Name',
    instanceNameLabel: 'Instance Name',
    instanceNamePlaceholder: 'e.g., WHISPER-California',
    whisperNamingHelper: 'Instance names are auto-generated based on your geography selection',
    description: 'Description',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Describe your proposal...',
    submit: 'Submit Proposal',
    submitButton: 'Submit Proposal',
    submitting: 'Submitting...',
    cancelButton: 'Cancel',
    checkingAvailability: 'Checking availability...',
    nameAvailable: 'Instance name is available',
    nameTaken: 'Instance name is already taken',
    nameRequired: 'Instance name is required',
    descriptionRequired: 'Description is required',
    stateRequired: 'State is required',
    countyRequired: 'County is required',
    submitSuccess: 'Proposal submitted successfully',
    submitError: 'Failed to submit proposal',
  },
  reportIssue: {
    title: 'Report Issue',
    sectionTitle: 'Report an Issue',
    sectionDescription: 'Help improve your community by reporting issues that need attention.',
    reportIssueCta: 'Report Issue',
  },
  profile: {
    pageTitle: 'Profile',
    title: 'Profile',
    pageDescription: 'Manage your profile information and settings',
    setupTitle: 'Welcome to Whisper',
    setupDescription: 'Let\'s set up your profile to get started',
    authRequired: 'Please log in to view your profile',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    nameRequired: 'Name is required',
    imageLabel: 'Profile Image',
    uploadImage: 'Upload Image',
    changeImage: 'Change Image',
    removeImage: 'Remove',
    imageHelper: 'PNG, JPG, or WebP. Max 2MB.',
    imageInvalidType: 'Please upload a valid image file',
    imageTooLarge: 'Image must be less than 2MB',
    saveButton: 'Save Profile',
    saving: 'Saving...',
    saveSuccess: 'Profile saved successfully',
    saveError: 'Failed to save profile',
    contributionPointsLabel: 'Contribution Points',
    contributionPointsHelper: 'Points are for tracking participation only—no token value in Phase 1',
  },
  admin: {
    pageTitle: 'Admin Moderation',
    pageDescription: 'Review and moderate community proposals',
    authRequired: 'Admin access required',
    authDescription: 'You must be logged in as an administrator to access this page.',
    loadingMessage: 'Loading moderation queue...',
    errorMessage: 'Failed to load moderation queue',
    emptyQueue: 'No items in moderation queue',
    emptyQueueDescription: 'All proposals have been reviewed.',
    refreshButton: 'Refresh',
    approveButton: 'Approve',
    rejectButton: 'Reject',
    hideButton: 'Hide',
    deleteButton: 'Delete',
    approving: 'Approving...',
    rejecting: 'Rejecting...',
    hiding: 'Hiding...',
    deleting: 'Deleting...',
    approveSuccess: 'Proposal approved',
    rejectSuccess: 'Proposal rejected',
    hideSuccess: 'Proposal hidden',
    deleteSuccess: 'Proposal deleted',
    approveError: 'Failed to approve proposal',
    rejectError: 'Failed to reject proposal',
    hideError: 'Failed to hide proposal',
    deleteError: 'Failed to delete proposal',
    confirmDelete: 'Are you sure you want to delete this proposal? This action cannot be undone.',
    confirmHide: 'Are you sure you want to hide this proposal from the moderation queue?',
    contributionLogsTitle: 'Contribution Logs',
    contributionLogsDescription: 'View all user contribution activity',
    contributionLogsEmpty: 'No contribution logs found',
    contributionLogsError: 'Failed to load contribution logs',
    contributionLogsRefresh: 'Refresh Logs',
    contributionLogsLoadMore: 'Load More',
    userSearchLabel: 'Search by User Principal',
    userSearchPlaceholder: 'Enter user principal ID...',
    userSearchButton: 'Search',
    userLogsEmpty: 'No contribution logs found for this user',
  },
  geography: {
    pageTitle: 'Geography',
    pageDescription: 'Explore geographic data and instances',
    backToHome: 'Back to Home',
    backButton: 'Back to Home',
  },
  secretary: {
    greeting: 'Hello! I\'m the Secretary. How can I help you today?',
    menuTitle: 'What would you like to do?',
    discoverabilityTitle: 'Meet the Secretary',
    discoverabilityDescription: 'Your AI assistant for navigating Whisper. Ask questions, report issues, or explore your community.',
    discoverabilityButton: 'Open Secretary',
    nudgeTitle: 'Meet the Secretary',
    nudgeDescription: 'Your AI assistant for navigating Whisper. Ask questions, report issues, or explore your community.',
    nudgeButton: 'Open Secretary',
    reportIssueTopIssuesPrompt: 'Here are the most common issues reported in your area. Would you like to report one of these, or describe a different issue?',
    reportIssueNoTopIssues: 'No common issues found for this location yet. Please describe the issue you\'d like to report.',
    reportIssueTopIssuesError: 'I couldn\'t load the top issues for this location. Please describe the issue you\'d like to report.',
    reportIssue: {
      loading: 'Looking up top issues for your location...',
      prompt: 'Here are the most common issues reported in your area. Would you like to report one of these, or describe a different issue?',
      empty: 'No common issues found for this location yet. Please describe the issue you\'d like to report.',
      error: 'I couldn\'t load the top issues for this location. Please describe the issue you\'d like to report.',
    },
  },
  footer: {
    builtWith: 'Built with',
    love: 'love',
    using: 'using',
    caffeineLink: 'caffeine.ai',
    allRightsReserved: 'All rights reserved.',
  },
};
