export const uiCopy = {
  product: {
    name: 'Whisper',
    tagline: 'Decentralized civic engagement for everyone',
  },
  common: {
    close: 'Close',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    back: 'Back',
  },
  navigation: {
    home: 'Home',
    proposals: 'Proposals',
    createInstance: 'Create Instance',
    admin: 'Admin',
    profile: 'Profile',
    geography: 'Geography',
  },
  hero: {
    title: 'Of the People. By the People. For the People.',
    subtitle: 'Whisper is the decentralized platform where citizens report issues, collaborate openly, and resolve them together — rewarding real effort, guaranteeing transparency, and rebuilding trust in local governance from the ground up.',
    primaryCta: 'Get Started',
    secondaryCta: 'Report Issue',
    getStartedCta: 'Get Started',
  },
  features: {
    title: 'Why Whisper?',
    feature1Title: 'Community-Driven',
    feature1Description: 'Every voice matters. Propose, discuss, and vote on local initiatives.',
    feature2Title: 'Transparent & Secure',
    feature2Description: 'Built on blockchain technology for immutable records and trust.',
    feature3Title: 'Scalable Governance',
    feature3Description: 'From neighborhoods to nations, Whisper scales with your community.',
    feature4Title: 'AI-Powered Assistant',
    feature4Description: 'Meet the Secretary—your guide to navigating civic engagement.',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
    loginPrompt: 'Please log in to continue',
    loginDescription: 'You need to be authenticated to access this feature.',
  },
  proposals: {
    title: 'Proposals',
    description: 'Browse and explore community proposals',
    viewAll: 'View All Proposals',
    noProposals: 'No proposals yet',
    noProposalsDescription: 'Be the first to create a proposal for your community.',
    createProposal: 'Create Proposal',
    status: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
    },
    proposer: 'Proposer',
    geography: 'Geography',
    geographyLabel: 'Geography',
    levelLabel: 'Level',
    stateLabel: 'State',
    countyLabel: 'County',
    population: 'Population',
    populationLabel: 'Population',
    area: 'Area',
    viewDetailsButton: 'View Details',
    openIssueProjectButton: 'Open Issue Project',
    refreshButton: 'Refresh',
    loadingMessage: 'Loading proposals...',
    errorMessage: 'Failed to load proposals',
    retryButton: 'Retry',
    emptyState: 'No proposals available',
  },
  createInstance: {
    title: 'Create Instance',
    description: 'Create a new Whisper instance for your community',
    yourCityOnWhisper: 'Your City on Whisper',
    yourCityDescription: 'Discover if your city, county, or state already has a Whisper instance, or become a founding citizen.',
    discoverYourCity: 'Discover Your City',
    getStartedTitle: 'Ready to Get Started?',
    getStartedDescription: 'Create a new Whisper instance for your community or explore existing proposals.',
    openSecretary: 'Open Secretary',
    selectState: 'Select State',
    selectCounty: 'Select County',
    selectPlace: 'Select Place (Optional)',
    stateLabel: 'State',
    countyLabel: 'County',
    placeLabel: 'Place (Optional)',
    instanceName: 'Instance Name',
    instanceNameLabel: 'Instance Name',
    instanceNamePlaceholder: 'e.g., WHISPER-California',
    whisperNamingHelper: 'Instance names are auto-generated based on your geography selection',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Describe your proposal...',
    submit: 'Submit Proposal',
    submitButton: 'Submit Proposal',
    submitting: 'Submitting...',
    cancelButton: 'Cancel',
    checkingAvailability: 'Checking availability...',
    nameAvailable: 'Instance name is available',
    nameTaken: 'Instance name is already taken',
    nameError: 'Error checking name availability',
    submitSuccess: 'Proposal submitted successfully!',
    submitError: 'Failed to submit proposal',
    validationError: 'Please fill in all required fields',
  },
  reportIssue: {
    title: 'Report Issue',
    sectionTitle: 'Report an Issue',
    sectionDescription: 'Help improve your community by reporting issues and concerns.',
    reportIssueCta: 'Report Issue',
  },
  secretary: {
    title: 'Secretary',
    greeting: 'Hello! I\'m the Secretary.',
    greetingDescription: 'I can help you navigate Whisper, create proposals, and report issues.',
    openButton: 'Open Secretary',
    dismissButton: 'Dismiss',
    nudgeTitle: 'Meet the Secretary',
    nudgeDescription: 'Your AI assistant for navigating Whisper and getting things done.',
    nudgeButton: 'Get Started',
    reportIssueTopIssuesError: 'Unable to load top issues for this location',
    reportIssueNoTopIssues: 'No top issues found for this location',
  },
  profile: {
    title: 'Profile',
    contributionPointsLabel: 'Contribution Points',
    contributionPointsHelper: 'Earn points by contributing to your community',
    contributionPointsZeroFallback: 'Start earning points by creating proposals, adding comments, or uploading evidence.',
  },
  governance: {
    title: 'Governance',
    description: 'Participate in governance by creating and voting on proposals',
    createButton: 'Create Proposal',
    createDialogTitle: 'Create Governance Proposal',
    createDialogDescription: 'Submit a new proposal for community governance',
    titleLabel: 'Title',
    titlePlaceholder: 'Enter proposal title',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Describe your proposal in detail',
    submitButton: 'Submit Proposal',
    submitting: 'Submitting...',
    createSuccess: 'Governance proposal created successfully',
    createError: 'Failed to create governance proposal',
    emptyState: 'No governance proposals yet. Create the first one!',
    errorMessage: 'Failed to load governance proposals',
    voteTalliesLabel: 'Vote Tallies',
    approvedLabel: 'Approved',
    rejectedLabel: 'Rejected',
    castVoteLabel: 'Cast Your Vote',
    approveButton: 'Approve',
    rejectButton: 'Reject',
    votingLabel: 'Voting...',
    voteApproveSuccess: 'Vote recorded: Approved',
    voteRejectSuccess: 'Vote recorded: Rejected',
    voteError: 'Failed to record vote',
    authRequired: 'Please log in to participate in governance',
    alreadyVoted: 'You have already voted on this proposal',
    votingClosed: 'Voting is closed for this proposal',
  },
  geography: {
    pageTitle: 'Geography',
    pageDescription: 'Explore geographic data and boundaries',
    backButton: 'Back to Home',
  },
  contributionLogs: {
    title: 'Contribution Logs',
    description: 'View and manage contribution activity',
    filterByActionType: 'Filter by Action Type',
    noLogs: 'No contribution logs found',
    previousPage: 'Previous',
    nextPage: 'Next',
  },
  footer: {
    allRightsReserved: 'All rights reserved.',
    builtWith: 'Built with',
    using: 'using',
  },
};
