/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const USHierarchyLevel = IDL.Variant({
  'country' : IDL.Null,
  'state' : IDL.Null,
  'place' : IDL.Null,
  'county' : IDL.Null,
});
export const Proposal = IDL.Record({
  'status' : IDL.Text,
  'geographyLevel' : USHierarchyLevel,
  'squareMeters' : IDL.Nat,
  'description' : IDL.Text,
  'state' : IDL.Text,
  'proposer' : IDL.Principal,
  'instanceName' : IDL.Text,
  'county' : IDL.Text,
  'censusBoundaryId' : IDL.Text,
  'population2020' : IDL.Text,
});
export const CensusStateCode = IDL.Text;
export const HierarchicalGeoId = IDL.Text;
export const USState = IDL.Record({
  'censusLandAreaSqMeters' : IDL.Nat,
  'fipsCode' : CensusStateCode,
  'hierarchicalId' : HierarchicalGeoId,
  'shortName' : IDL.Text,
  'longName' : IDL.Text,
  'censusWaterAreaSqMeters' : IDL.Nat,
  'censusAcreage' : IDL.Nat,
  'termType' : IDL.Text,
});
export const ProfileImage = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'profileImage' : IDL.Opt(ProfileImage),
  'name' : IDL.Text,
});
export const USPlace = IDL.Record({
  'countyFullName' : IDL.Text,
  'hierarchicalId' : HierarchicalGeoId,
  'fullName' : IDL.Text,
  'censusCensusFipsCode' : IDL.Text,
  'censusLandKm2' : IDL.Int,
  'shortName' : IDL.Text,
  'censusWaterKm2' : IDL.Int,
  'censusAcres' : IDL.Int,
  'uspsPlaceType' : IDL.Text,
  'population' : IDL.Opt(IDL.Nat),
  'censusPlaceType' : IDL.Text,
  'censusStateCode' : CensusStateCode,
});
export const GeoId = IDL.Text;
export const USCounty = IDL.Record({
  'censusLandAreaSqMeters' : IDL.Text,
  'fipsCode' : IDL.Text,
  'hierarchicalId' : HierarchicalGeoId,
  'censusFipsStateCode' : IDL.Text,
  'censusAreaAcres' : IDL.Text,
  'fullName' : IDL.Text,
  'shortName' : IDL.Text,
  'censusWaterAreaSqMeters' : IDL.Text,
  'population2010' : IDL.Text,
});
export const DeletionRequest = IDL.Record({
  'user' : IDL.Principal,
  'requestedAt' : IDL.Int,
});
export const SecretaryCategorySuggestion = IDL.Record({
  'statesByGeoId' : IDL.Vec(USState),
  'searchTerm' : IDL.Text,
  'locationLevel' : USHierarchyLevel,
  'proposedCategories' : IDL.Vec(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const USGeographyDataChunk = IDL.Record({
  'states' : IDL.Vec(USState),
  'places' : IDL.Vec(USPlace),
  'counties' : IDL.Vec(USCounty),
});
export const SubmitProposalResult = IDL.Variant({
  'error' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({ 'proposal' : Proposal }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAdminModerationQueue' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
      ['query'],
    ),
  'getAllCityComplaintCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllCountyComplaintCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllProposals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
      ['query'],
    ),
  'getAllStateComplaintCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllStates' : IDL.Func([], [IDL.Vec(USState)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCityById' : IDL.Func([HierarchicalGeoId], [IDL.Opt(USPlace)], ['query']),
  'getCityComplaintSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCountiesForState' : IDL.Func([GeoId], [IDL.Vec(USCounty)], ['query']),
  'getCountyById' : IDL.Func(
      [HierarchicalGeoId],
      [IDL.Opt(USCounty)],
      ['query'],
    ),
  'getCountyComplaintSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getDeletionRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, DeletionRequest))],
      ['query'],
    ),
  'getPlacesForCounty' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
  'getPlacesForState' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
  'getProposal' : IDL.Func([IDL.Text], [IDL.Opt(Proposal)], ['query']),
  'getSecretaryCategorySuggestion' : IDL.Func(
      [IDL.Text, USHierarchyLevel],
      [SecretaryCategorySuggestion],
      ['query'],
    ),
  'getStateById' : IDL.Func([HierarchicalGeoId], [IDL.Opt(USState)], ['query']),
  'getStateComplaintSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getTasks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Task))],
      ['query'],
    ),
  'getTop50IssuesForLocation' : IDL.Func(
      [USHierarchyLevel, IDL.Opt(HierarchicalGeoId)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hideProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'ingestUSGeographyData' : IDL.Func([IDL.Vec(USGeographyDataChunk)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInstanceNameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isParent' : IDL.Func([IDL.Principal, IDL.Principal], [IDL.Bool], ['query']),
  'processDeletionRequest' : IDL.Func([IDL.Principal], [], []),
  'requestDeletion' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSimilarCityNames' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(USPlace)],
      ['query'],
    ),
  'submitProposal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        USHierarchyLevel,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [SubmitProposalResult],
      [],
    ),
  'updateProposalStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateTaskStatus' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const USHierarchyLevel = IDL.Variant({
    'country' : IDL.Null,
    'state' : IDL.Null,
    'place' : IDL.Null,
    'county' : IDL.Null,
  });
  const Proposal = IDL.Record({
    'status' : IDL.Text,
    'geographyLevel' : USHierarchyLevel,
    'squareMeters' : IDL.Nat,
    'description' : IDL.Text,
    'state' : IDL.Text,
    'proposer' : IDL.Principal,
    'instanceName' : IDL.Text,
    'county' : IDL.Text,
    'censusBoundaryId' : IDL.Text,
    'population2020' : IDL.Text,
  });
  const CensusStateCode = IDL.Text;
  const HierarchicalGeoId = IDL.Text;
  const USState = IDL.Record({
    'censusLandAreaSqMeters' : IDL.Nat,
    'fipsCode' : CensusStateCode,
    'hierarchicalId' : HierarchicalGeoId,
    'shortName' : IDL.Text,
    'longName' : IDL.Text,
    'censusWaterAreaSqMeters' : IDL.Nat,
    'censusAcreage' : IDL.Nat,
    'termType' : IDL.Text,
  });
  const ProfileImage = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'profileImage' : IDL.Opt(ProfileImage),
    'name' : IDL.Text,
  });
  const USPlace = IDL.Record({
    'countyFullName' : IDL.Text,
    'hierarchicalId' : HierarchicalGeoId,
    'fullName' : IDL.Text,
    'censusCensusFipsCode' : IDL.Text,
    'censusLandKm2' : IDL.Int,
    'shortName' : IDL.Text,
    'censusWaterKm2' : IDL.Int,
    'censusAcres' : IDL.Int,
    'uspsPlaceType' : IDL.Text,
    'population' : IDL.Opt(IDL.Nat),
    'censusPlaceType' : IDL.Text,
    'censusStateCode' : CensusStateCode,
  });
  const GeoId = IDL.Text;
  const USCounty = IDL.Record({
    'censusLandAreaSqMeters' : IDL.Text,
    'fipsCode' : IDL.Text,
    'hierarchicalId' : HierarchicalGeoId,
    'censusFipsStateCode' : IDL.Text,
    'censusAreaAcres' : IDL.Text,
    'fullName' : IDL.Text,
    'shortName' : IDL.Text,
    'censusWaterAreaSqMeters' : IDL.Text,
    'population2010' : IDL.Text,
  });
  const DeletionRequest = IDL.Record({
    'user' : IDL.Principal,
    'requestedAt' : IDL.Int,
  });
  const SecretaryCategorySuggestion = IDL.Record({
    'statesByGeoId' : IDL.Vec(USState),
    'searchTerm' : IDL.Text,
    'locationLevel' : USHierarchyLevel,
    'proposedCategories' : IDL.Vec(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  const USGeographyDataChunk = IDL.Record({
    'states' : IDL.Vec(USState),
    'places' : IDL.Vec(USPlace),
    'counties' : IDL.Vec(USCounty),
  });
  const SubmitProposalResult = IDL.Variant({
    'error' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({ 'proposal' : Proposal }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAdminModerationQueue' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
        ['query'],
      ),
    'getAllCityComplaintCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllCountyComplaintCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllProposals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
        ['query'],
      ),
    'getAllStateComplaintCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllStates' : IDL.Func([], [IDL.Vec(USState)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCityById' : IDL.Func(
        [HierarchicalGeoId],
        [IDL.Opt(USPlace)],
        ['query'],
      ),
    'getCityComplaintSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCountiesForState' : IDL.Func([GeoId], [IDL.Vec(USCounty)], ['query']),
    'getCountyById' : IDL.Func(
        [HierarchicalGeoId],
        [IDL.Opt(USCounty)],
        ['query'],
      ),
    'getCountyComplaintSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getDeletionRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, DeletionRequest))],
        ['query'],
      ),
    'getPlacesForCounty' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
    'getPlacesForState' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
    'getProposal' : IDL.Func([IDL.Text], [IDL.Opt(Proposal)], ['query']),
    'getSecretaryCategorySuggestion' : IDL.Func(
        [IDL.Text, USHierarchyLevel],
        [SecretaryCategorySuggestion],
        ['query'],
      ),
    'getStateById' : IDL.Func(
        [HierarchicalGeoId],
        [IDL.Opt(USState)],
        ['query'],
      ),
    'getStateComplaintSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getTasks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Task))],
        ['query'],
      ),
    'getTop50IssuesForLocation' : IDL.Func(
        [USHierarchyLevel, IDL.Opt(HierarchicalGeoId)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hideProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'ingestUSGeographyData' : IDL.Func([IDL.Vec(USGeographyDataChunk)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInstanceNameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isParent' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'processDeletionRequest' : IDL.Func([IDL.Principal], [], []),
    'requestDeletion' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSimilarCityNames' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(USPlace)],
        ['query'],
      ),
    'submitProposal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          USHierarchyLevel,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [SubmitProposalResult],
        [],
      ),
    'updateProposalStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateTaskStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };