/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const USHierarchyLevel = IDL.Variant({
  'country' : IDL.Null,
  'state' : IDL.Null,
  'place' : IDL.Null,
  'county' : IDL.Null,
});
export const ContributionLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'pointsAwarded' : IDL.Nat,
  'actionType' : IDL.Text,
  'referenceId' : IDL.Opt(IDL.Text),
  'rewardType' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Opt(IDL.Text),
  'invalidated' : IDL.Bool,
  'contributor' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HierarchicalGeoId = IDL.Text;
export const USCounty = IDL.Record({
  'censusLandAreaSqMeters' : IDL.Text,
  'fipsCode' : IDL.Text,
  'hierarchicalId' : HierarchicalGeoId,
  'censusFipsStateCode' : IDL.Text,
  'censusAreaAcres' : IDL.Text,
  'fullName' : IDL.Text,
  'shortName' : IDL.Text,
  'censusWaterAreaSqMeters' : IDL.Text,
  'population2010' : IDL.Text,
});
export const CensusStateCode = IDL.Text;
export const USPlace = IDL.Record({
  'countyFullName' : IDL.Text,
  'hierarchicalId' : HierarchicalGeoId,
  'fullName' : IDL.Text,
  'censusCensusFipsCode' : IDL.Text,
  'censusLandKm2' : IDL.Int,
  'shortName' : IDL.Text,
  'censusWaterKm2' : IDL.Int,
  'censusAcres' : IDL.Int,
  'uspsPlaceType' : IDL.Text,
  'population' : IDL.Opt(IDL.Nat),
  'censusPlaceType' : IDL.Text,
  'censusStateCode' : CensusStateCode,
});
export const USState = IDL.Record({
  'censusLandAreaSqMeters' : IDL.Nat,
  'fipsCode' : CensusStateCode,
  'hierarchicalId' : HierarchicalGeoId,
  'shortName' : IDL.Text,
  'longName' : IDL.Text,
  'censusWaterAreaSqMeters' : IDL.Nat,
  'censusAcreage' : IDL.Nat,
  'termType' : IDL.Text,
});
export const Proposal = IDL.Record({
  'status' : IDL.Text,
  'geographyLevel' : USHierarchyLevel,
  'squareMeters' : IDL.Nat,
  'description' : IDL.Text,
  'state' : IDL.Text,
  'proposer' : IDL.Principal,
  'instanceName' : IDL.Text,
  'county' : IDL.Text,
  'censusBoundaryId' : IDL.Text,
  'population2020' : IDL.Text,
});
export const ContributionSummary = IDL.Record({
  'totalCityPoints' : IDL.Nat,
  'totalBountyPoints' : IDL.Nat,
  'totalVotingPoints' : IDL.Nat,
  'totalTokenPoints' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'contributor' : IDL.Principal,
});
export const StakingRecord = IDL.Record({
  'availableBalance' : IDL.Nat,
  'pendingRewards' : IDL.Nat,
  'lockedBalance' : IDL.Nat,
  'totalStaked' : IDL.Nat,
});
export const ProfileImage = IDL.Vec(IDL.Nat8);
export const TokenBalance = IDL.Record({
  'staked' : IDL.Nat,
  'total' : IDL.Nat,
  'voting' : IDL.Nat,
  'bounty' : IDL.Nat,
});
export const ContributionPoints = IDL.Record({
  'token' : IDL.Nat,
  'city' : IDL.Nat,
  'voting' : IDL.Nat,
  'bounty' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'profileImage' : IDL.Opt(ProfileImage),
  'name' : IDL.Text,
  'tokenBalance' : TokenBalance,
  'contributionPoints' : ContributionPoints,
});
export const ContributionCriteria = IDL.Record({
  'actionType' : IDL.Text,
  'rewardType' : IDL.Text,
  'eligibilityCriteria' : IDL.Text,
  'points' : IDL.Nat,
});
export const GeoId = IDL.Text;
export const SecretaryCategorySuggestion = IDL.Record({
  'statesByGeoId' : IDL.Vec(USState),
  'searchTerm' : IDL.Text,
  'locationLevel' : USHierarchyLevel,
  'proposedCategories' : IDL.Vec(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const GovernanceProposalStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'executed' : IDL.Null,
});
export const GovernanceProposal = IDL.Record({
  'id' : IDL.Nat,
  'status' : GovernanceProposalStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'proposer' : IDL.Principal,
});
export const USGeographyDataChunk = IDL.Record({
  'states' : IDL.Vec(USState),
  'places' : IDL.Vec(USPlace),
  'counties' : IDL.Vec(USCounty),
});
export const LogContributionEventError = IDL.Variant({
  'referenceIdEmpty' : IDL.Null,
  'referenceIdRequired' : IDL.Null,
  'duplicateContribution' : IDL.Null,
  'invalidActionType' : IDL.Null,
});
export const SubmitProposalResult = IDL.Variant({
  'error' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({ 'proposal' : Proposal }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContributionPoints' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addOrUpdateLocationBasedIssues' : IDL.Func(
      [USHierarchyLevel, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'adminBurnWSP' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetContributionLogs' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ContributionLogEntry)))],
      ['query'],
    ),
  'adminGetUserContributionLogs' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(ContributionLogEntry)],
      ['query'],
    ),
  'adminInvalidateContribution' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminMintWSP' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backend_getIssueCategoriesByHierarchyLevel' : IDL.Func(
      [USHierarchyLevel, IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'backend_getUSCountyByHierarchicalId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(USCounty)],
      ['query'],
    ),
  'backend_getUSPlaceByHierarchicalId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(USPlace)],
      ['query'],
    ),
  'backend_getUSStateByHierarchicalId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(USState)],
      ['query'],
    ),
  'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAdminModerationQueue' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
      ['query'],
    ),
  'getAllCityComplaintCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllCountyComplaintCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllProposals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
      ['query'],
    ),
  'getAllStateComplaintCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllStates' : IDL.Func([], [IDL.Vec(USState)], ['query']),
  'getCallerContributionHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ContributionLogEntry)],
      ['query'],
    ),
  'getCallerContributionSummary' : IDL.Func(
      [],
      [ContributionSummary],
      ['query'],
    ),
  'getCallerStakingRecord' : IDL.Func([], [IDL.Opt(StakingRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCityById' : IDL.Func([IDL.Text], [IDL.Opt(USPlace)], ['query']),
  'getCityComplaintSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getContributionCriteria' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ContributionCriteria))],
      ['query'],
    ),
  'getCountiesForState' : IDL.Func([GeoId], [IDL.Vec(USCounty)], ['query']),
  'getCountyById' : IDL.Func([IDL.Text], [IDL.Opt(USCounty)], ['query']),
  'getCountyComplaintSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPlacesForCounty' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
  'getPlacesForState' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
  'getProposal' : IDL.Func([IDL.Text], [IDL.Opt(Proposal)], ['query']),
  'getSecretaryCategorySuggestion' : IDL.Func(
      [IDL.Text, USHierarchyLevel],
      [SecretaryCategorySuggestion],
      ['query'],
    ),
  'getSecretaryCategorySuggestions' : IDL.Func(
      [IDL.Text, USHierarchyLevel],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getStateById' : IDL.Func([IDL.Text], [IDL.Opt(USState)], ['query']),
  'getStateComplaintSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getTasks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Task))],
      ['query'],
    ),
  'getTopIssuesForLocation' : IDL.Func(
      [USHierarchyLevel, IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStakingRecord' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StakingRecord)],
      ['query'],
    ),
  'governanceCreateProposal' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'governanceGetProposal' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(GovernanceProposal)],
      ['query'],
    ),
  'governanceListProposals' : IDL.Func(
      [],
      [IDL.Vec(GovernanceProposal)],
      ['query'],
    ),
  'governanceVote' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'hideProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'icrc1_balance_of' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'icrc1_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
  'icrc1_transfer' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'ingestUSGeographyData' : IDL.Func([IDL.Vec(USGeographyDataChunk)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInstanceNameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isParent' : IDL.Func([IDL.Principal, IDL.Principal], [IDL.Bool], ['query']),
  'logContributionEvent' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : LogContributionEventError })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setContributionCriteria' : IDL.Func(
      [IDL.Text, ContributionCriteria],
      [],
      [],
    ),
  'submitProposal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        USHierarchyLevel,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [SubmitProposalResult],
      [],
    ),
  'updateProposalStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateTaskStatus' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const USHierarchyLevel = IDL.Variant({
    'country' : IDL.Null,
    'state' : IDL.Null,
    'place' : IDL.Null,
    'county' : IDL.Null,
  });
  const ContributionLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'pointsAwarded' : IDL.Nat,
    'actionType' : IDL.Text,
    'referenceId' : IDL.Opt(IDL.Text),
    'rewardType' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Opt(IDL.Text),
    'invalidated' : IDL.Bool,
    'contributor' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HierarchicalGeoId = IDL.Text;
  const USCounty = IDL.Record({
    'censusLandAreaSqMeters' : IDL.Text,
    'fipsCode' : IDL.Text,
    'hierarchicalId' : HierarchicalGeoId,
    'censusFipsStateCode' : IDL.Text,
    'censusAreaAcres' : IDL.Text,
    'fullName' : IDL.Text,
    'shortName' : IDL.Text,
    'censusWaterAreaSqMeters' : IDL.Text,
    'population2010' : IDL.Text,
  });
  const CensusStateCode = IDL.Text;
  const USPlace = IDL.Record({
    'countyFullName' : IDL.Text,
    'hierarchicalId' : HierarchicalGeoId,
    'fullName' : IDL.Text,
    'censusCensusFipsCode' : IDL.Text,
    'censusLandKm2' : IDL.Int,
    'shortName' : IDL.Text,
    'censusWaterKm2' : IDL.Int,
    'censusAcres' : IDL.Int,
    'uspsPlaceType' : IDL.Text,
    'population' : IDL.Opt(IDL.Nat),
    'censusPlaceType' : IDL.Text,
    'censusStateCode' : CensusStateCode,
  });
  const USState = IDL.Record({
    'censusLandAreaSqMeters' : IDL.Nat,
    'fipsCode' : CensusStateCode,
    'hierarchicalId' : HierarchicalGeoId,
    'shortName' : IDL.Text,
    'longName' : IDL.Text,
    'censusWaterAreaSqMeters' : IDL.Nat,
    'censusAcreage' : IDL.Nat,
    'termType' : IDL.Text,
  });
  const Proposal = IDL.Record({
    'status' : IDL.Text,
    'geographyLevel' : USHierarchyLevel,
    'squareMeters' : IDL.Nat,
    'description' : IDL.Text,
    'state' : IDL.Text,
    'proposer' : IDL.Principal,
    'instanceName' : IDL.Text,
    'county' : IDL.Text,
    'censusBoundaryId' : IDL.Text,
    'population2020' : IDL.Text,
  });
  const ContributionSummary = IDL.Record({
    'totalCityPoints' : IDL.Nat,
    'totalBountyPoints' : IDL.Nat,
    'totalVotingPoints' : IDL.Nat,
    'totalTokenPoints' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'contributor' : IDL.Principal,
  });
  const StakingRecord = IDL.Record({
    'availableBalance' : IDL.Nat,
    'pendingRewards' : IDL.Nat,
    'lockedBalance' : IDL.Nat,
    'totalStaked' : IDL.Nat,
  });
  const ProfileImage = IDL.Vec(IDL.Nat8);
  const TokenBalance = IDL.Record({
    'staked' : IDL.Nat,
    'total' : IDL.Nat,
    'voting' : IDL.Nat,
    'bounty' : IDL.Nat,
  });
  const ContributionPoints = IDL.Record({
    'token' : IDL.Nat,
    'city' : IDL.Nat,
    'voting' : IDL.Nat,
    'bounty' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'profileImage' : IDL.Opt(ProfileImage),
    'name' : IDL.Text,
    'tokenBalance' : TokenBalance,
    'contributionPoints' : ContributionPoints,
  });
  const ContributionCriteria = IDL.Record({
    'actionType' : IDL.Text,
    'rewardType' : IDL.Text,
    'eligibilityCriteria' : IDL.Text,
    'points' : IDL.Nat,
  });
  const GeoId = IDL.Text;
  const SecretaryCategorySuggestion = IDL.Record({
    'statesByGeoId' : IDL.Vec(USState),
    'searchTerm' : IDL.Text,
    'locationLevel' : USHierarchyLevel,
    'proposedCategories' : IDL.Vec(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  const GovernanceProposalStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'executed' : IDL.Null,
  });
  const GovernanceProposal = IDL.Record({
    'id' : IDL.Nat,
    'status' : GovernanceProposalStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'proposer' : IDL.Principal,
  });
  const USGeographyDataChunk = IDL.Record({
    'states' : IDL.Vec(USState),
    'places' : IDL.Vec(USPlace),
    'counties' : IDL.Vec(USCounty),
  });
  const LogContributionEventError = IDL.Variant({
    'referenceIdEmpty' : IDL.Null,
    'referenceIdRequired' : IDL.Null,
    'duplicateContribution' : IDL.Null,
    'invalidActionType' : IDL.Null,
  });
  const SubmitProposalResult = IDL.Variant({
    'error' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({ 'proposal' : Proposal }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContributionPoints' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addOrUpdateLocationBasedIssues' : IDL.Func(
        [USHierarchyLevel, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'adminBurnWSP' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetContributionLogs' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ContributionLogEntry)))],
        ['query'],
      ),
    'adminGetUserContributionLogs' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(ContributionLogEntry)],
        ['query'],
      ),
    'adminInvalidateContribution' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminMintWSP' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backend_getIssueCategoriesByHierarchyLevel' : IDL.Func(
        [USHierarchyLevel, IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'backend_getUSCountyByHierarchicalId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(USCounty)],
        ['query'],
      ),
    'backend_getUSPlaceByHierarchicalId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(USPlace)],
        ['query'],
      ),
    'backend_getUSStateByHierarchicalId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(USState)],
        ['query'],
      ),
    'createTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAdminModerationQueue' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
        ['query'],
      ),
    'getAllCityComplaintCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllCountyComplaintCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllProposals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Proposal))],
        ['query'],
      ),
    'getAllStateComplaintCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllStates' : IDL.Func([], [IDL.Vec(USState)], ['query']),
    'getCallerContributionHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ContributionLogEntry)],
        ['query'],
      ),
    'getCallerContributionSummary' : IDL.Func(
        [],
        [ContributionSummary],
        ['query'],
      ),
    'getCallerStakingRecord' : IDL.Func(
        [],
        [IDL.Opt(StakingRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCityById' : IDL.Func([IDL.Text], [IDL.Opt(USPlace)], ['query']),
    'getCityComplaintSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getContributionCriteria' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ContributionCriteria))],
        ['query'],
      ),
    'getCountiesForState' : IDL.Func([GeoId], [IDL.Vec(USCounty)], ['query']),
    'getCountyById' : IDL.Func([IDL.Text], [IDL.Opt(USCounty)], ['query']),
    'getCountyComplaintSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPlacesForCounty' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
    'getPlacesForState' : IDL.Func([GeoId], [IDL.Vec(USPlace)], ['query']),
    'getProposal' : IDL.Func([IDL.Text], [IDL.Opt(Proposal)], ['query']),
    'getSecretaryCategorySuggestion' : IDL.Func(
        [IDL.Text, USHierarchyLevel],
        [SecretaryCategorySuggestion],
        ['query'],
      ),
    'getSecretaryCategorySuggestions' : IDL.Func(
        [IDL.Text, USHierarchyLevel],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getStateById' : IDL.Func([IDL.Text], [IDL.Opt(USState)], ['query']),
    'getStateComplaintSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getTasks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Task))],
        ['query'],
      ),
    'getTopIssuesForLocation' : IDL.Func(
        [USHierarchyLevel, IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStakingRecord' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StakingRecord)],
        ['query'],
      ),
    'governanceCreateProposal' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'governanceGetProposal' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(GovernanceProposal)],
        ['query'],
      ),
    'governanceListProposals' : IDL.Func(
        [],
        [IDL.Vec(GovernanceProposal)],
        ['query'],
      ),
    'governanceVote' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'hideProposal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'icrc1_balance_of' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'icrc1_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
    'icrc1_transfer' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'ingestUSGeographyData' : IDL.Func([IDL.Vec(USGeographyDataChunk)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInstanceNameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isParent' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'logContributionEvent' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : LogContributionEventError })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setContributionCriteria' : IDL.Func(
        [IDL.Text, ContributionCriteria],
        [],
        [],
      ),
    'submitProposal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          USHierarchyLevel,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [SubmitProposalResult],
        [],
      ),
    'updateProposalStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateTaskStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };