/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CensusStateCode = string;
export interface ContributionCriteria {
  'actionType' : string,
  'rewardType' : string,
  'eligibilityCriteria' : string,
  'points' : bigint,
}
export interface ContributionLogEntry {
  'id' : bigint,
  'pointsAwarded' : bigint,
  'actionType' : string,
  'referenceId' : [] | [string],
  'rewardType' : string,
  'timestamp' : bigint,
  'details' : [] | [string],
  'contributor' : Principal,
}
export interface ContributionPoints {
  'token' : bigint,
  'city' : bigint,
  'voting' : bigint,
  'bounty' : bigint,
}
export interface ContributionSummary {
  'totalCityPoints' : bigint,
  'totalBountyPoints' : bigint,
  'totalVotingPoints' : bigint,
  'totalTokenPoints' : bigint,
  'totalPoints' : bigint,
  'contributor' : Principal,
}
export type GeoId = string;
export type HierarchicalGeoId = string;
export type LogContributionEventError = { 'referenceIdEmpty' : null } |
  { 'referenceIdRequired' : null } |
  { 'duplicateContribution' : null } |
  { 'invalidActionType' : null };
export type ProfileImage = Uint8Array;
export interface Proposal {
  'status' : string,
  'geographyLevel' : USHierarchyLevel,
  'squareMeters' : bigint,
  'description' : string,
  'state' : string,
  'proposer' : Principal,
  'instanceName' : string,
  'county' : string,
  'censusBoundaryId' : string,
  'population2020' : string,
}
export interface SecretaryCategorySuggestion {
  'statesByGeoId' : Array<USState>,
  'searchTerm' : string,
  'locationLevel' : USHierarchyLevel,
  'proposedCategories' : Array<string>,
}
export type SubmitProposalResult = { 'error' : { 'message' : string } } |
  { 'success' : { 'proposal' : Proposal } };
export interface Task {
  'id' : bigint,
  'completed' : boolean,
  'description' : string,
}
export interface TokenBalance {
  'staked' : bigint,
  'total' : bigint,
  'voting' : bigint,
  'bounty' : bigint,
}
export interface USCounty {
  'censusLandAreaSqMeters' : string,
  'fipsCode' : string,
  'hierarchicalId' : HierarchicalGeoId,
  'censusFipsStateCode' : string,
  'censusAreaAcres' : string,
  'fullName' : string,
  'shortName' : string,
  'censusWaterAreaSqMeters' : string,
  'population2010' : string,
}
export interface USGeographyDataChunk {
  'states' : Array<USState>,
  'places' : Array<USPlace>,
  'counties' : Array<USCounty>,
}
export type USHierarchyLevel = { 'country' : null } |
  { 'state' : null } |
  { 'place' : null } |
  { 'county' : null };
export interface USPlace {
  'countyFullName' : string,
  'hierarchicalId' : HierarchicalGeoId,
  'fullName' : string,
  'censusCensusFipsCode' : string,
  'censusLandKm2' : bigint,
  'shortName' : string,
  'censusWaterKm2' : bigint,
  'censusAcres' : bigint,
  'uspsPlaceType' : string,
  'population' : [] | [bigint],
  'censusPlaceType' : string,
  'censusStateCode' : CensusStateCode,
}
export interface USState {
  'censusLandAreaSqMeters' : bigint,
  'fipsCode' : CensusStateCode,
  'hierarchicalId' : HierarchicalGeoId,
  'shortName' : string,
  'longName' : string,
  'censusWaterAreaSqMeters' : bigint,
  'censusAcreage' : bigint,
  'termType' : string,
}
export interface UserProfile {
  'profileImage' : [] | [ProfileImage],
  'name' : string,
  'tokenBalance' : TokenBalance,
  'contributionPoints' : ContributionPoints,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContributionPoints' : ActorMethod<[bigint, string, string], undefined>,
  'addOrUpdateLocationBasedIssues' : ActorMethod<
    [USHierarchyLevel, [] | [string], Array<string>],
    undefined
  >,
  'adminGetContributionLogs' : ActorMethod<
    [bigint, bigint],
    Array<[Principal, Array<ContributionLogEntry>]>
  >,
  'adminGetUserContributionLogs' : ActorMethod<
    [Principal, bigint],
    Array<ContributionLogEntry>
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backend_getIssueCategoriesByHierarchyLevel' : ActorMethod<
    [USHierarchyLevel, [] | [string]],
    Array<string>
  >,
  'backend_getUSCountyByHierarchicalId' : ActorMethod<
    [string],
    [] | [USCounty]
  >,
  'backend_getUSPlaceByHierarchicalId' : ActorMethod<[string], [] | [USPlace]>,
  'backend_getUSStateByHierarchicalId' : ActorMethod<[string], [] | [USState]>,
  'createTask' : ActorMethod<[string, string], bigint>,
  'deleteProposal' : ActorMethod<[string], boolean>,
  'getAdminModerationQueue' : ActorMethod<[], Array<[string, Proposal]>>,
  'getAllCityComplaintCategories' : ActorMethod<[], Array<string>>,
  'getAllCountyComplaintCategories' : ActorMethod<[], Array<string>>,
  'getAllProposals' : ActorMethod<[], Array<[string, Proposal]>>,
  'getAllStateComplaintCategories' : ActorMethod<[], Array<string>>,
  'getAllStates' : ActorMethod<[], Array<USState>>,
  'getCallerContributionHistory' : ActorMethod<
    [bigint],
    Array<ContributionLogEntry>
  >,
  'getCallerContributionSummary' : ActorMethod<[], ContributionSummary>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCityById' : ActorMethod<[string], [] | [USPlace]>,
  'getCityComplaintSuggestions' : ActorMethod<[string], Array<string>>,
  'getContributionCriteria' : ActorMethod<
    [],
    Array<[string, ContributionCriteria]>
  >,
  'getCountiesForState' : ActorMethod<[GeoId], Array<USCounty>>,
  'getCountyById' : ActorMethod<[string], [] | [USCounty]>,
  'getCountyComplaintSuggestions' : ActorMethod<[string], Array<string>>,
  'getPlacesForCounty' : ActorMethod<[GeoId], Array<USPlace>>,
  'getPlacesForState' : ActorMethod<[GeoId], Array<USPlace>>,
  'getProposal' : ActorMethod<[string], [] | [Proposal]>,
  'getSecretaryCategorySuggestion' : ActorMethod<
    [string, USHierarchyLevel],
    SecretaryCategorySuggestion
  >,
  'getSecretaryCategorySuggestions' : ActorMethod<
    [string, USHierarchyLevel],
    Array<string>
  >,
  'getStateById' : ActorMethod<[string], [] | [USState]>,
  'getStateComplaintSuggestions' : ActorMethod<[string], Array<string>>,
  'getTasks' : ActorMethod<[string], Array<[bigint, Task]>>,
  'getTopIssuesForLocation' : ActorMethod<
    [USHierarchyLevel, [] | [string]],
    Array<string>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hideProposal' : ActorMethod<[string], boolean>,
  'ingestUSGeographyData' : ActorMethod<
    [Array<USGeographyDataChunk>],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isInstanceNameTaken' : ActorMethod<[string], boolean>,
  'isParent' : ActorMethod<[Principal, Principal], boolean>,
  'logContributionEvent' : ActorMethod<
    [string, [] | [string], [] | [string]],
    { 'ok' : bigint } |
      { 'err' : LogContributionEventError }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContributionCriteria' : ActorMethod<
    [string, ContributionCriteria],
    undefined
  >,
  'submitProposal' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      USHierarchyLevel,
      string,
      bigint,
      string,
    ],
    SubmitProposalResult
  >,
  'updateProposalStatus' : ActorMethod<[string, string], boolean>,
  'updateTaskStatus' : ActorMethod<[string, bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];