/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContributionLogEntry {
    id: bigint;
    pointsAwarded: bigint;
    actionType: string;
    referenceId?: string;
    rewardType: string;
    timestamp: bigint;
    details?: string;
    invalidated: boolean;
    contributor: Principal;
}
export interface SecretaryCategorySuggestion {
    statesByGeoId: Array<USState>;
    searchTerm: string;
    locationLevel: USHierarchyLevel;
    proposedCategories: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ContributionCriteria {
    actionType: string;
    rewardType: string;
    eligibilityCriteria: string;
    points: bigint;
}
export type SubmitProposalResult = {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        proposal: Proposal;
    };
};
export interface Task {
    id: bigint;
    completed: boolean;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ContributionPoints {
    token: bigint;
    city: bigint;
    voting: bigint;
    bounty: bigint;
}
export interface Proposal {
    status: string;
    geographyLevel: USHierarchyLevel;
    squareMeters: bigint;
    description: string;
    state: string;
    proposer: Principal;
    instanceName: string;
    county: string;
    censusBoundaryId: string;
    population2020: string;
}
export type CensusStateCode = string;
export type GeoId = string;
export interface USGeographyDataChunk {
    states: Array<USState>;
    places: Array<USPlace>;
    counties: Array<USCounty>;
}
export interface USPlace {
    countyFullName: string;
    hierarchicalId: HierarchicalGeoId;
    fullName: string;
    censusCensusFipsCode: string;
    censusLandKm2: bigint;
    shortName: string;
    censusWaterKm2: bigint;
    censusAcres: bigint;
    uspsPlaceType: string;
    population?: bigint;
    censusPlaceType: string;
    censusStateCode: CensusStateCode;
}
export interface ContributionSummary {
    totalCityPoints: bigint;
    totalBountyPoints: bigint;
    totalVotingPoints: bigint;
    totalTokenPoints: bigint;
    totalPoints: bigint;
    contributor: Principal;
}
export interface GovernanceProposal {
    id: bigint;
    status: GovernanceProposalStatus;
    title: string;
    createdAt: bigint;
    description: string;
    proposer: Principal;
}
export interface USCounty {
    censusLandAreaSqMeters: string;
    fipsCode: string;
    hierarchicalId: HierarchicalGeoId;
    censusFipsStateCode: string;
    censusAreaAcres: string;
    fullName: string;
    shortName: string;
    censusWaterAreaSqMeters: string;
    population2010: string;
}
export interface USState {
    censusLandAreaSqMeters: bigint;
    fipsCode: CensusStateCode;
    hierarchicalId: HierarchicalGeoId;
    shortName: string;
    longName: string;
    censusWaterAreaSqMeters: bigint;
    censusAcreage: bigint;
    termType: string;
}
export type ProfileImage = Uint8Array;
export type HierarchicalGeoId = string;
export interface TokenBalance {
    staked: bigint;
    total: bigint;
    voting: bigint;
    bounty: bigint;
}
export interface UserProfile {
    profileImage?: ProfileImage;
    name: string;
    tokenBalance: TokenBalance;
    contributionPoints: ContributionPoints;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum GovernanceProposalStatus {
    active = "active",
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    executed = "executed"
}
export enum LogContributionEventError {
    referenceIdEmpty = "referenceIdEmpty",
    referenceIdRequired = "referenceIdRequired",
    duplicateContribution = "duplicateContribution",
    invalidActionType = "invalidActionType"
}
export enum USHierarchyLevel {
    country = "country",
    state = "state",
    place = "place",
    county = "county"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContributionPoints(points: bigint, rewardType: string, actionType: string): Promise<void>;
    addOrUpdateLocationBasedIssues(locationLevel: USHierarchyLevel, locationId: string | null, issues: Array<string>): Promise<void>;
    adminBurnWSP(account: Principal, amount: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetContributionLogs(offset: bigint, limit: bigint): Promise<Array<[Principal, Array<ContributionLogEntry>]>>;
    adminGetUserContributionLogs(user: Principal, limit: bigint): Promise<Array<ContributionLogEntry>>;
    adminInvalidateContribution(contributor: Principal, entryId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminMintWSP(recipient: Principal, amount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backend_getIssueCategoriesByHierarchyLevel(locationLevel: USHierarchyLevel, locationId: string | null): Promise<Array<string>>;
    backend_getUSCountyByHierarchicalId(hierarchicalId: string): Promise<USCounty | null>;
    backend_getUSPlaceByHierarchicalId(hierarchicalId: string): Promise<USPlace | null>;
    backend_getUSStateByHierarchicalId(hierarchicalId: string): Promise<USState | null>;
    createTask(proposalId: string, description: string): Promise<bigint>;
    deleteProposal(instanceName: string): Promise<boolean>;
    getAdminModerationQueue(): Promise<Array<[string, Proposal]>>;
    getAllCityComplaintCategories(): Promise<Array<string>>;
    getAllCountyComplaintCategories(): Promise<Array<string>>;
    getAllProposals(): Promise<Array<[string, Proposal]>>;
    getAllStateComplaintCategories(): Promise<Array<string>>;
    getAllStates(): Promise<Array<USState>>;
    getCallerContributionHistory(limit: bigint): Promise<Array<ContributionLogEntry>>;
    getCallerContributionSummary(): Promise<ContributionSummary>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCityById(cityId: string): Promise<USPlace | null>;
    getCityComplaintSuggestions(searchTerm: string): Promise<Array<string>>;
    getContributionCriteria(): Promise<Array<[string, ContributionCriteria]>>;
    getCountiesForState(stateGeoId: GeoId): Promise<Array<USCounty>>;
    getCountyById(countyId: string): Promise<USCounty | null>;
    getCountyComplaintSuggestions(searchTerm: string): Promise<Array<string>>;
    getPlacesForCounty(countyGeoId: GeoId): Promise<Array<USPlace>>;
    getPlacesForState(stateGeoId: GeoId): Promise<Array<USPlace>>;
    getProposal(instanceName: string): Promise<Proposal | null>;
    getSecretaryCategorySuggestion(searchTerm: string, locationLevel: USHierarchyLevel): Promise<SecretaryCategorySuggestion>;
    getSecretaryCategorySuggestions(searchTerm: string, locationLevel: USHierarchyLevel): Promise<Array<string>>;
    getStateById(stateId: string): Promise<USState | null>;
    getStateComplaintSuggestions(searchTerm: string): Promise<Array<string>>;
    getTasks(proposalId: string): Promise<Array<[bigint, Task]>>;
    getTopIssuesForLocation(locationLevel: USHierarchyLevel, locationId: string | null): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    governanceCreateProposal(title: string, description: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    governanceGetProposal(proposalId: bigint): Promise<GovernanceProposal | null>;
    governanceListProposals(): Promise<Array<GovernanceProposal>>;
    governanceVote(proposalId: bigint, approve: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    hideProposal(instanceName: string): Promise<boolean>;
    icrc1_balance_of(account: Principal): Promise<bigint>;
    icrc1_total_supply(): Promise<bigint>;
    icrc1_transfer(to: Principal, amount: bigint): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    ingestUSGeographyData(data: Array<USGeographyDataChunk>): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isInstanceNameTaken(instanceName: string): Promise<boolean>;
    isParent(_childId: Principal, parentId: Principal): Promise<boolean>;
    logContributionEvent(actionType: string, referenceId: string | null, details: string | null): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: LogContributionEventError;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setContributionCriteria(actionType: string, criteria: ContributionCriteria): Promise<void>;
    submitProposal(description: string, instanceName: string, status: string, state: string, county: string, geographyLevel: USHierarchyLevel, censusBoundaryId: string, squareMeters: bigint, population2020: string): Promise<SubmitProposalResult>;
    updateProposalStatus(instanceName: string, newStatus: string): Promise<boolean>;
    updateTaskStatus(proposalId: string, taskId: bigint, completed: boolean): Promise<boolean>;
}
import type { CensusStateCode as _CensusStateCode, ContributionLogEntry as _ContributionLogEntry, ContributionPoints as _ContributionPoints, GovernanceProposal as _GovernanceProposal, GovernanceProposalStatus as _GovernanceProposalStatus, HierarchicalGeoId as _HierarchicalGeoId, LogContributionEventError as _LogContributionEventError, ProfileImage as _ProfileImage, Proposal as _Proposal, SecretaryCategorySuggestion as _SecretaryCategorySuggestion, SubmitProposalResult as _SubmitProposalResult, TokenBalance as _TokenBalance, USCounty as _USCounty, USGeographyDataChunk as _USGeographyDataChunk, USHierarchyLevel as _USHierarchyLevel, USPlace as _USPlace, USState as _USState, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContributionPoints(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContributionPoints(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContributionPoints(arg0, arg1, arg2);
            return result;
        }
    }
    async addOrUpdateLocationBasedIssues(arg0: USHierarchyLevel, arg1: string | null, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateLocationBasedIssues(to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateLocationBasedIssues(to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async adminBurnWSP(arg0: Principal, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBurnWSP(arg0, arg1);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBurnWSP(arg0, arg1);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetContributionLogs(arg0: bigint, arg1: bigint): Promise<Array<[Principal, Array<ContributionLogEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetContributionLogs(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetContributionLogs(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserContributionLogs(arg0: Principal, arg1: bigint): Promise<Array<ContributionLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserContributionLogs(arg0, arg1);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserContributionLogs(arg0, arg1);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminInvalidateContribution(arg0: Principal, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminInvalidateContribution(arg0, arg1);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminInvalidateContribution(arg0, arg1);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminMintWSP(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMintWSP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMintWSP(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backend_getIssueCategoriesByHierarchyLevel(arg0: USHierarchyLevel, arg1: string | null): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.backend_getIssueCategoriesByHierarchyLevel(to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backend_getIssueCategoriesByHierarchyLevel(to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backend_getUSCountyByHierarchicalId(arg0: string): Promise<USCounty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.backend_getUSCountyByHierarchicalId(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backend_getUSCountyByHierarchicalId(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async backend_getUSPlaceByHierarchicalId(arg0: string): Promise<USPlace | null> {
        if (this.processError) {
            try {
                const result = await this.actor.backend_getUSPlaceByHierarchicalId(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backend_getUSPlaceByHierarchicalId(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async backend_getUSStateByHierarchicalId(arg0: string): Promise<USState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.backend_getUSStateByHierarchicalId(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backend_getUSStateByHierarchicalId(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1);
            return result;
        }
    }
    async deleteProposal(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProposal(arg0);
            return result;
        }
    }
    async getAdminModerationQueue(): Promise<Array<[string, Proposal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminModerationQueue();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminModerationQueue();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCityComplaintCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCityComplaintCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCityComplaintCategories();
            return result;
        }
    }
    async getAllCountyComplaintCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCountyComplaintCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCountyComplaintCategories();
            return result;
        }
    }
    async getAllProposals(): Promise<Array<[string, Proposal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProposals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProposals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStateComplaintCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStateComplaintCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStateComplaintCategories();
            return result;
        }
    }
    async getAllStates(): Promise<Array<USState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStates();
            return result;
        }
    }
    async getCallerContributionHistory(arg0: bigint): Promise<Array<ContributionLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerContributionHistory(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerContributionHistory(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerContributionSummary(): Promise<ContributionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerContributionSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerContributionSummary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCityById(arg0: string): Promise<USPlace | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCityComplaintSuggestions(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityComplaintSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityComplaintSuggestions(arg0);
            return result;
        }
    }
    async getContributionCriteria(): Promise<Array<[string, ContributionCriteria]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributionCriteria();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributionCriteria();
            return result;
        }
    }
    async getCountiesForState(arg0: GeoId): Promise<Array<USCounty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountiesForState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountiesForState(arg0);
            return result;
        }
    }
    async getCountyById(arg0: string): Promise<USCounty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountyById(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountyById(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCountyComplaintSuggestions(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountyComplaintSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountyComplaintSuggestions(arg0);
            return result;
        }
    }
    async getPlacesForCounty(arg0: GeoId): Promise<Array<USPlace>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlacesForCounty(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlacesForCounty(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlacesForState(arg0: GeoId): Promise<Array<USPlace>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlacesForState(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlacesForState(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProposal(arg0: string): Promise<Proposal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProposal(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProposal(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecretaryCategorySuggestion(arg0: string, arg1: USHierarchyLevel): Promise<SecretaryCategorySuggestion> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecretaryCategorySuggestion(arg0, to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_SecretaryCategorySuggestion_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecretaryCategorySuggestion(arg0, to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_SecretaryCategorySuggestion_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecretaryCategorySuggestions(arg0: string, arg1: USHierarchyLevel): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecretaryCategorySuggestions(arg0, to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecretaryCategorySuggestions(arg0, to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getStateById(arg0: string): Promise<USState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStateById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStateById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStateComplaintSuggestions(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStateComplaintSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStateComplaintSuggestions(arg0);
            return result;
        }
    }
    async getTasks(arg0: string): Promise<Array<[bigint, Task]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return result;
        }
    }
    async getTopIssuesForLocation(arg0: USHierarchyLevel, arg1: string | null): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopIssuesForLocation(to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopIssuesForLocation(to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async governanceCreateProposal(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.governanceCreateProposal(arg0, arg1);
                return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.governanceCreateProposal(arg0, arg1);
            return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async governanceGetProposal(arg0: bigint): Promise<GovernanceProposal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.governanceGetProposal(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.governanceGetProposal(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async governanceListProposals(): Promise<Array<GovernanceProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.governanceListProposals();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.governanceListProposals();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async governanceVote(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.governanceVote(arg0, arg1);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.governanceVote(arg0, arg1);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async hideProposal(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hideProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideProposal(arg0);
            return result;
        }
    }
    async icrc1_balance_of(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc1_balance_of(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc1_balance_of(arg0);
            return result;
        }
    }
    async icrc1_total_supply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc1_total_supply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc1_total_supply();
            return result;
        }
    }
    async icrc1_transfer(arg0: Principal, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc1_transfer(arg0, arg1);
                return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc1_transfer(arg0, arg1);
            return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async ingestUSGeographyData(arg0: Array<USGeographyDataChunk>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ingestUSGeographyData(to_candid_vec_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ingestUSGeographyData(to_candid_vec_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isInstanceNameTaken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInstanceNameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInstanceNameTaken(arg0);
            return result;
        }
    }
    async isParent(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isParent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isParent(arg0, arg1);
            return result;
        }
    }
    async logContributionEvent(arg0: string, arg1: string | null, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: LogContributionEventError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.logContributionEvent(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logContributionEvent(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setContributionCriteria(arg0: string, arg1: ContributionCriteria): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setContributionCriteria(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContributionCriteria(arg0, arg1);
            return result;
        }
    }
    async submitProposal(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: USHierarchyLevel, arg6: string, arg7: bigint, arg8: string): Promise<SubmitProposalResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProposal(arg0, arg1, arg2, arg3, arg4, to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
                return from_candid_SubmitProposalResult_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProposal(arg0, arg1, arg2, arg3, arg4, to_candid_USHierarchyLevel_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
            return from_candid_SubmitProposalResult_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProposalStatus(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProposalStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProposalStatus(arg0, arg1);
            return result;
        }
    }
    async updateTaskStatus(arg0: string, arg1: bigint, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ContributionLogEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributionLogEntry): ContributionLogEntry {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_GovernanceProposalStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GovernanceProposalStatus): GovernanceProposalStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_GovernanceProposal_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GovernanceProposal): GovernanceProposal {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_LogContributionEventError_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogContributionEventError): LogContributionEventError {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Proposal_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Proposal): Proposal {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SecretaryCategorySuggestion_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecretaryCategorySuggestion): SecretaryCategorySuggestion {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitProposalResult_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitProposalResult): SubmitProposalResult {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_USHierarchyLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _USHierarchyLevel): USHierarchyLevel {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_USPlace_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _USPlace): USPlace {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_USCounty]): USCounty | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_USPlace]): USPlace | null {
    return value.length === 0 ? null : from_candid_USPlace_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_USState]): USState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileImage]): ProfileImage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Proposal]): Proposal | null {
    return value.length === 0 ? null : from_candid_Proposal_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GovernanceProposal]): GovernanceProposal | null {
    return value.length === 0 ? null : from_candid_GovernanceProposal_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pointsAwarded: bigint;
    actionType: string;
    referenceId: [] | [string];
    rewardType: string;
    timestamp: bigint;
    details: [] | [string];
    invalidated: boolean;
    contributor: Principal;
}): {
    id: bigint;
    pointsAwarded: bigint;
    actionType: string;
    referenceId?: string;
    rewardType: string;
    timestamp: bigint;
    details?: string;
    invalidated: boolean;
    contributor: Principal;
} {
    return {
        id: value.id,
        pointsAwarded: value.pointsAwarded,
        actionType: value.actionType,
        referenceId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.referenceId)),
        rewardType: value.rewardType,
        timestamp: value.timestamp,
        details: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.details)),
        invalidated: value.invalidated,
        contributor: value.contributor
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    countyFullName: string;
    hierarchicalId: _HierarchicalGeoId;
    fullName: string;
    censusCensusFipsCode: string;
    censusLandKm2: bigint;
    shortName: string;
    censusWaterKm2: bigint;
    censusAcres: bigint;
    uspsPlaceType: string;
    population: [] | [bigint];
    censusPlaceType: string;
    censusStateCode: _CensusStateCode;
}): {
    countyFullName: string;
    hierarchicalId: HierarchicalGeoId;
    fullName: string;
    censusCensusFipsCode: string;
    censusLandKm2: bigint;
    shortName: string;
    censusWaterKm2: bigint;
    censusAcres: bigint;
    uspsPlaceType: string;
    population?: bigint;
    censusPlaceType: string;
    censusStateCode: CensusStateCode;
} {
    return {
        countyFullName: value.countyFullName,
        hierarchicalId: value.hierarchicalId,
        fullName: value.fullName,
        censusCensusFipsCode: value.censusCensusFipsCode,
        censusLandKm2: value.censusLandKm2,
        shortName: value.shortName,
        censusWaterKm2: value.censusWaterKm2,
        censusAcres: value.censusAcres,
        uspsPlaceType: value.uspsPlaceType,
        population: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.population)),
        censusPlaceType: value.censusPlaceType,
        censusStateCode: value.censusStateCode
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    geographyLevel: _USHierarchyLevel;
    squareMeters: bigint;
    description: string;
    state: string;
    proposer: Principal;
    instanceName: string;
    county: string;
    censusBoundaryId: string;
    population2020: string;
}): {
    status: string;
    geographyLevel: USHierarchyLevel;
    squareMeters: bigint;
    description: string;
    state: string;
    proposer: Principal;
    instanceName: string;
    county: string;
    censusBoundaryId: string;
    population2020: string;
} {
    return {
        status: value.status,
        geographyLevel: from_candid_USHierarchyLevel_n29(_uploadFile, _downloadFile, value.geographyLevel),
        squareMeters: value.squareMeters,
        description: value.description,
        state: value.state,
        proposer: value.proposer,
        instanceName: value.instanceName,
        county: value.county,
        censusBoundaryId: value.censusBoundaryId,
        population2020: value.population2020
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileImage: [] | [_ProfileImage];
    name: string;
    tokenBalance: _TokenBalance;
    contributionPoints: _ContributionPoints;
}): {
    profileImage?: ProfileImage;
    name: string;
    tokenBalance: TokenBalance;
    contributionPoints: ContributionPoints;
} {
    return {
        profileImage: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name,
        tokenBalance: value.tokenBalance,
        contributionPoints: value.contributionPoints
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    statesByGeoId: Array<_USState>;
    searchTerm: string;
    locationLevel: _USHierarchyLevel;
    proposedCategories: Array<string>;
}): {
    statesByGeoId: Array<USState>;
    searchTerm: string;
    locationLevel: USHierarchyLevel;
    proposedCategories: Array<string>;
} {
    return {
        statesByGeoId: value.statesByGeoId,
        searchTerm: value.searchTerm,
        locationLevel: from_candid_USHierarchyLevel_n29(_uploadFile, _downloadFile, value.locationLevel),
        proposedCategories: value.proposedCategories
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _GovernanceProposalStatus;
    title: string;
    createdAt: bigint;
    description: string;
    proposer: Principal;
}): {
    id: bigint;
    status: GovernanceProposalStatus;
    title: string;
    createdAt: bigint;
    description: string;
    proposer: Principal;
} {
    return {
        id: value.id,
        status: from_candid_GovernanceProposalStatus_n45(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        proposer: value.proposer
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposal: _Proposal;
}): {
    proposal: Proposal;
} {
    return {
        proposal: from_candid_Proposal_n27(_uploadFile, _downloadFile, value.proposal)
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_ContributionLogEntry>]): [Principal, Array<ContributionLogEntry>] {
    return [
        value[0],
        from_candid_vec_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Proposal]): [string, Proposal] {
    return [
        value[0],
        from_candid_Proposal_n27(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: null;
} | {
    state: null;
} | {
    place: null;
} | {
    county: null;
}): USHierarchyLevel {
    return "country" in value ? USHierarchyLevel.country : "state" in value ? USHierarchyLevel.state : "place" in value ? USHierarchyLevel.place : "county" in value ? USHierarchyLevel.county : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    executed: null;
}): GovernanceProposalStatus {
    return "active" in value ? GovernanceProposalStatus.active : "pending" in value ? GovernanceProposalStatus.pending : "approved" in value ? GovernanceProposalStatus.approved : "rejected" in value ? GovernanceProposalStatus.rejected : "executed" in value ? GovernanceProposalStatus.executed : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: _LogContributionEventError;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: LogContributionEventError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_LogContributionEventError_n55(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referenceIdEmpty: null;
} | {
    referenceIdRequired: null;
} | {
    duplicateContribution: null;
} | {
    invalidActionType: null;
}): LogContributionEventError {
    return "referenceIdEmpty" in value ? LogContributionEventError.referenceIdEmpty : "referenceIdRequired" in value ? LogContributionEventError.referenceIdRequired : "duplicateContribution" in value ? LogContributionEventError.duplicateContribution : "invalidActionType" in value ? LogContributionEventError.invalidActionType : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: {
        message: string;
    };
} | {
    success: {
        proposal: _Proposal;
    };
}): {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        proposal: Proposal;
    };
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_record_n61(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_ContributionLogEntry>]>): Array<[Principal, Array<ContributionLogEntry>]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContributionLogEntry>): Array<ContributionLogEntry> {
    return value.map((x)=>from_candid_ContributionLogEntry_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Proposal]>): Array<[string, Proposal]> {
    return value.map((x)=>from_candid_tuple_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_USPlace>): Array<USPlace> {
    return value.map((x)=>from_candid_USPlace_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GovernanceProposal>): Array<GovernanceProposal> {
    return value.map((x)=>from_candid_GovernanceProposal_n43(_uploadFile, _downloadFile, x));
}
function to_candid_USGeographyDataChunk_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: USGeographyDataChunk): _USGeographyDataChunk {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_USHierarchyLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: USHierarchyLevel): _USHierarchyLevel {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_USPlace_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: USPlace): _USPlace {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    states: Array<USState>;
    places: Array<USPlace>;
    counties: Array<USCounty>;
}): {
    states: Array<_USState>;
    places: Array<_USPlace>;
    counties: Array<_USCounty>;
} {
    return {
        states: value.states,
        places: to_candid_vec_n51(_uploadFile, _downloadFile, value.places),
        counties: value.counties
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    countyFullName: string;
    hierarchicalId: HierarchicalGeoId;
    fullName: string;
    censusCensusFipsCode: string;
    censusLandKm2: bigint;
    shortName: string;
    censusWaterKm2: bigint;
    censusAcres: bigint;
    uspsPlaceType: string;
    population?: bigint;
    censusPlaceType: string;
    censusStateCode: CensusStateCode;
}): {
    countyFullName: string;
    hierarchicalId: _HierarchicalGeoId;
    fullName: string;
    censusCensusFipsCode: string;
    censusLandKm2: bigint;
    shortName: string;
    censusWaterKm2: bigint;
    censusAcres: bigint;
    uspsPlaceType: string;
    population: [] | [bigint];
    censusPlaceType: string;
    censusStateCode: _CensusStateCode;
} {
    return {
        countyFullName: value.countyFullName,
        hierarchicalId: value.hierarchicalId,
        fullName: value.fullName,
        censusCensusFipsCode: value.censusCensusFipsCode,
        censusLandKm2: value.censusLandKm2,
        shortName: value.shortName,
        censusWaterKm2: value.censusWaterKm2,
        censusAcres: value.censusAcres,
        uspsPlaceType: value.uspsPlaceType,
        population: value.population ? candid_some(value.population) : candid_none(),
        censusPlaceType: value.censusPlaceType,
        censusStateCode: value.censusStateCode
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileImage?: ProfileImage;
    name: string;
    tokenBalance: TokenBalance;
    contributionPoints: ContributionPoints;
}): {
    profileImage: [] | [_ProfileImage];
    name: string;
    tokenBalance: _TokenBalance;
    contributionPoints: _ContributionPoints;
} {
    return {
        profileImage: value.profileImage ? candid_some(value.profileImage) : candid_none(),
        name: value.name,
        tokenBalance: value.tokenBalance,
        contributionPoints: value.contributionPoints
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: USHierarchyLevel): {
    country: null;
} | {
    state: null;
} | {
    place: null;
} | {
    county: null;
} {
    return value == USHierarchyLevel.country ? {
        country: null
    } : value == USHierarchyLevel.state ? {
        state: null
    } : value == USHierarchyLevel.place ? {
        place: null
    } : value == USHierarchyLevel.county ? {
        county: null
    } : value;
}
function to_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<USGeographyDataChunk>): Array<_USGeographyDataChunk> {
    return value.map((x)=>to_candid_USGeographyDataChunk_n49(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<USPlace>): Array<_USPlace> {
    return value.map((x)=>to_candid_USPlace_n52(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
